//
// Created by Екатерина Пак on 9/5/26.
//

#ifndef SIMPLE_NOTEPAD_PROJECT_NOTEPAD_EXCEPTION_H
#define SIMPLE_NOTEPAD_PROJECT_NOTEPAD_EXCEPTION_H

#endif //SIMPLE_NOTEPAD_PROJECT_NOTEPAD_EXCEPTION_H